#!/bin/bash
### ---
### name: 'NETWORK_GENERATION (Network generation and filtering)'
### outputs:
### - 'Networks/Metabolites2targets*.txt'
### - 'Networks/TFs2targets*.txt'
### - 'Networks/Lipids2targets*.txt'
### - 'Networks/Proteins2targets*.txt'
### - 'Networks/*2targets*.txt'
### - 'Networks/LemonNetwork_*.txt'
### - 'Networks/Cytoscape_*.txt'
### - 'Networks/*_distribution_plot_*.png'
### - 'Networks/Network_*_ranked_regulators_*.txt'
### - 'ModuleViewer_files/*'
### - 'ModuleViewer_files/sample_mapping.mvf'
### - 'Networks/specific_modules.txt'
### - 'Networks/Module_coherence_scores.txt'
### - 'Module_prioritization_coherence_*.txt'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_tree() {
    local pid=$1

    declare -a ALL_CHILDREN
    while read P PP;do
        ALL_CHILDREN[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    pstat() {
        local x_pid=$1
        local STATUS=$(2> /dev/null < /proc/$1/status grep -E 'Vm|ctxt')

        if [ $? = 0 ]; then
        local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
        local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
        local x_peak=$(echo "$STATUS" | grep -E 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
        local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
        local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
        fi
    }

    pwalk() {
        pstat $1
        for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
    }

    pwalk $1
}

nxf_stat() {
    cpu_stat=()
    nxf_tree $1

    declare -a sum=(0 0 0 0 0 0 0 0)
    local pid
    local i
    for pid in "${!cpu_stat[@]}"; do
        local row=(${cpu_stat[pid]})
        [ $NXF_DEBUG = 1 ] && echo "++ stat mem=${row[*]}"
        for i in "${!row[@]}"; do
        if [ $i != 0 ]; then
            sum[i]=$((sum[i]+row[i]))
        fi
        done
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat SUM=${sum[*]}"

    for i in {1..7}; do
        if [ ${sum[i]} -lt ${cpu_peak[i]} ]; then
            sum[i]=${cpu_peak[i]}
        else
            cpu_peak[i]=${sum[i]}
        fi
    done

    [ $NXF_DEBUG = 1 ] && echo -e "++ stat PEAK=${sum[*]}\n"
    nxf_stat_ret=(${sum[*]})
}

nxf_mem_watch() {
    set -o pipefail
    local pid=$1
    local trace_file=.command.trace
    local count=0;
    declare -a cpu_stat=(0 0 0 0 0 0 0 0)
    declare -a cpu_peak=(0 0 0 0 0 0 0 0)
    local mem_tot=$(< /proc/meminfo grep MemTotal | awk '{print $2}')
    local timeout
    local DONE
    local STOP=''

    [ $NXF_DEBUG = 1 ] && nxf_sleep 0.2 && ps fx

    while true; do
        nxf_stat $pid
        if [ $count -lt 10 ]; then timeout=1;
        elif [ $count -lt 120 ]; then timeout=5;
        else timeout=30;
        fi
        read -t $timeout -r DONE || true
        [[ $DONE ]] && break
        if [ ! -e /proc/$pid ]; then
            [ ! $STOP ] && STOP=$(nxf_date)
            [ $(($(nxf_date)-STOP)) -gt 10000 ] && break
        fi
        count=$((count+1))
    done

    printf "%s\n" \
        "%mem=${nxf_stat_ret[1]}" \
        "vmem=${nxf_stat_ret[2]}" \
        "rss=${nxf_stat_ret[3]}" \
        "peak_vmem=${nxf_stat_ret[4]}" \
        "peak_rss=${nxf_stat_ret[5]}" \
        "vol_ctxt=${nxf_stat_ret[6]}" \
        "inv_ctxt=${nxf_stat_ret[7]}" >> "$trace_file" || >&2 echo "Error: Failed to append to file: $trace_file"
}

nxf_write_trace() {
    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"
}

nxf_trace_mac() {
    local start_millis=$(nxf_date)

    /bin/bash -euo pipefail /home/borisvdm/repo/LemonIte/nextflow/work/4b/f6adec63587e40ae831940f37b9fdb/.command.sh

    local end_millis=$(nxf_date)
    local wall_time=$((end_millis-start_millis))
    local ucpu=''
    local cpu_model=''
    local io_stat1=('' '' '' '' '' '')
    nxf_write_trace
}

nxf_fd() {
    local FD=11
    while [ -e /proc/$$/fd/$FD ]; do FD=$((FD+1)); done
    echo $FD
}

nxf_trace_linux() {
    local pid=$$
    command -v ps &>/dev/null || { >&2 echo "Command 'ps' required by nextflow to collect task metrics cannot be found"; exit 1; }
    local num_cpus=$(< /proc/cpuinfo grep '^processor' -c)
    local cpu_model=$(< /proc/cpuinfo grep '^model name' | head -n 1 | awk 'BEGIN{FS="\t: "} { print $2 }')
    local tot_time0=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time0=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local io_stat0=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local start_millis=$(nxf_date)
    trap 'kill $mem_proc' ERR
    
    /bin/bash -euo pipefail /home/borisvdm/repo/LemonIte/nextflow/work/4b/f6adec63587e40ae831940f37b9fdb/.command.sh &
    local task=$!

    mem_fd=$(nxf_fd)
    eval "exec $mem_fd> >(nxf_mem_watch $task)"
    local mem_proc=$!

    wait $task

    local end_millis=$(nxf_date)
    local tot_time1=$(grep '^cpu ' /proc/stat | awk '{sum=$2+$3+$4+$5+$6+$7+$8+$9; printf "%.0f",sum}')
    local cpu_time1=$(2> /dev/null < /proc/$pid/stat awk '{printf "%.0f", ($16+$17)*10 }' || echo -n 'X')
    local ucpu=$(awk -v p1=$cpu_time1 -v p0=$cpu_time0 -v t1=$tot_time1 -v t0=$tot_time0 -v n=$num_cpus 'BEGIN { pct=(p1-p0)/(t1-t0)*100*n; printf("%.0f", pct>0 ? pct : 0) }' )

    local io_stat1=($(2> /dev/null < /proc/$pid/io sed 's/^.*:\s*//' | head -n 6 | tr '\n' ' ' || echo -n '0 0 0 0 0 0'))
    local i
    for i in {0..5}; do
        io_stat1[i]=$((io_stat1[i]-io_stat0[i]))
    done

    local wall_time=$((end_millis-start_millis))
    [ $NXF_DEBUG = 1 ] && echo "+++ STATS %CPU=$ucpu TIME=$wall_time I/O=${io_stat1[*]}"

    printf "%s\n" \
        "nextflow.trace/v2" \
        "realtime=$wall_time" \
        "%cpu=$ucpu" \
        "cpu_model=$cpu_model" \
        "rchar=${io_stat1[0]}" \
        "wchar=${io_stat1[1]}" \
        "syscr=${io_stat1[2]}" \
        "syscw=${io_stat1[3]}" \
        "read_bytes=${io_stat1[4]}" \
        "write_bytes=${io_stat1[5]}" >| "$trace_file" || >&2 echo "Error: Failed to write to file: $trace_file"

    [ -e /proc/$mem_proc ] && eval "echo 'DONE' >&$mem_fd" || true
    wait $mem_proc 2>/dev/null || true
    while [ -e /proc/$mem_proc ]; do nxf_sleep 0.1; done
}

nxf_trace() {
    local trace_file=.command.trace
    touch $trace_file
    if [[ $(uname) = Darwin ]]; then
        nxf_trace_mac
    else
        nxf_trace_linux
    fi
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/borisvdm/repo/LemonIte/nextflow/work/4b/f6adec63587e40ae831940f37b9fdb/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -euo pipefail /home/borisvdm/repo/LemonIte/nextflow/work/4b/f6adec63587e40ae831940f37b9fdb/.command.run nxf_trace
}

nxf_stage() {
    true
    # stage input files
    rm -f metabolites.txt
    rm -f LemonPreprocessed_proteomics.txt
    rm -f DESeq_groups.txt
    rm -f hPTMs.xml.gz
    rm -f name_mapping.tsv
    rm -f LemonPreprocessed_hPTM.txt
    rm -f hPTMs.allreg.txt
    rm -f clusterfile
    rm -f PCA_proteomics.pdf
    rm -f LemonPreprocessed_metabolomics.txt
    rm -f Metabolites.randomreg.txt
    rm -f PCA_hptm.pdf
    rm -f Metabolites.topreg.txt
    rm -f LemonPreprocessed_complete.txt
    rm -f hPTMs.randomreg.txt
    rm -f Metabolites.allreg.txt
    rm -f tight_clusters.txt
    rm -f hptms.txt
    rm -f Lemon_results
    rm -f hPTMs.topreg.txt
    rm -f PCA_metabolomics.pdf
    rm -f Metabolites.xml.gz
    rm -f LemonPreprocessed_expression.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/metabolites.txt metabolites.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/LemonPreprocessed_proteomics.txt LemonPreprocessed_proteomics.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/DESeq_groups.txt DESeq_groups.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/hPTMs.xml.gz hPTMs.xml.gz
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/name_mapping.tsv name_mapping.tsv
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/LemonPreprocessed_hPTM.txt LemonPreprocessed_hPTM.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/hPTMs.allreg.txt hPTMs.allreg.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/clusterfile clusterfile
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/PCA_proteomics.pdf PCA_proteomics.pdf
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/LemonPreprocessed_metabolomics.txt LemonPreprocessed_metabolomics.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/Metabolites.randomreg.txt Metabolites.randomreg.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/PCA_hptm.pdf PCA_hptm.pdf
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/Metabolites.topreg.txt Metabolites.topreg.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/LemonPreprocessed_complete.txt LemonPreprocessed_complete.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/hPTMs.randomreg.txt hPTMs.randomreg.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/Metabolites.allreg.txt Metabolites.allreg.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/tight_clusters.txt tight_clusters.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/hptms.txt hptms.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/Lemon_results Lemon_results
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/hPTMs.topreg.txt hPTMs.topreg.txt
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/PCA_metabolomics.pdf PCA_metabolomics.pdf
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Lemon_out/Metabolites.xml.gz Metabolites.xml.gz
    ln -s /home/borisvdm/repo/LemonIte/nextflow/work/c5/308931803293cf97fd48a4762118fe/Preprocessing/LemonPreprocessed_expression.txt LemonPreprocessed_expression.txt
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/borisvdm/repo/LemonIte/nextflow/work/4b/f6adec63587e40ae831940f37b9fdb/.command.begin
    set +u
    # conda environment
    source $(conda info --json | awk '/conda_prefix/ { gsub(/"|,/, "", $2); print $2 }')/bin/activate /home/borisvdm/Software/miniconda3/envs/LemonIte
    set -u
    export PYTHONNOUSERSITE="1"
    export R_PROFILE_USER="/.Rprofile"
    export R_ENVIRON_USER="/.Renviron"
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
