process POST_CLUSTERING {
    tag "LemonTree post-clustering analysis"
    publishDir "${(params.output_dir ?: (params.input_dir ? params.input_dir + '/results' : './results'))}/${(params.computed_run_id ?: (params.run_id ?: 'run_auto'))}/LemonTree", mode: 'copy', pattern: "Lemon_out/*"

    input:
    path lemontree_inputs
    path "Lemon_results/cluster_*"
    val run_id

    output:
    path "Lemon_out/*", emit: lemontree_outputs
    path "Preprocessing/*", emit: preprocessing_files

    script:
    """
    # Create Lemon_out directory and copy cluster results
    mkdir -p Lemon_out/Lemon_results
    
    # Copy cluster results to Lemon_results subdirectory
    # Note: cluster files can be either files or directories depending on LemonTree output
    for cluster_item in Lemon_results/cluster_*; do
        if [ -e "\$cluster_item" ]; then
            cp -r "\$cluster_item" Lemon_out/Lemon_results/
        fi
    done
    
    # Copy LemonTree input files to Preprocessing directory
    mkdir -p Preprocessing
    
    # List what we have available
    echo "=== Available staged files ==="
    ls -la
    echo "============================="
    
    # Copy all staged files to Preprocessing directory
    # Nextflow stages the files directly in the work directory
    for file in ${lemontree_inputs}; do
        cp "\$file" ./Preprocessing/
    done
    
    # Verify files were copied
    echo "=== Files in Preprocessing directory ==="
    ls -la ./Preprocessing/
    echo "========================================"
    
    # Run LemonTree post-clustering analysis (tight clusters and regulators)
    echo "Running LemonTree post-clustering analysis..."
    # Check host script first (allows updates without rebuilding container)
    if [ -f "${projectDir}/scripts/lemontree_post_clustering.sh" ]; then
        SCRIPT_PATH="${projectDir}/scripts/lemontree_post_clustering.sh"
    elif [ -f "/app/scripts/lemontree_post_clustering.sh" ]; then
        SCRIPT_PATH="/app/scripts/lemontree_post_clustering.sh"
    else
        echo "Error: lemontree_post_clustering.sh not found"
        exit 1
    fi
    bash \$SCRIPT_PATH \
        "${params.regulator_types}" \
        ${params.lemontree_jar} \
        . \
        "${params.organism}"
    
    # List generated files for debugging
    echo "=== Files generated by post-clustering ==="
    find Lemon_out -type f -name "*.txt" | head -20
    echo "=========================================="
    """

    stub:
    """
    mkdir -p Lemon_out/Lemon_results Preprocessing
    touch Lemon_out/clusterfile
    touch Lemon_out/Lovering.topreg.txt
    touch Preprocessing/DESeq_groups.txt
    """
}

process NETWORK_GENERATION {
    tag "Network generation and filtering"
    publishDir "${(params.output_dir ?: (params.input_dir ? params.input_dir + '/results' : './results'))}/${(params.computed_run_id ?: (params.run_id ?: 'run_auto'))}/LemonTree", mode: 'copy'

    input:
    path lemontree_outputs
    path preprocessing_files
    val run_id

    output:
    path "Networks/Metabolites2targets*.txt", emit: metabolites_targets, optional: true
    path "Networks/TFs2targets*.txt", emit: tf_targets, optional: true
    path "Networks/Lipids2targets*.txt", emit: lipids_targets, optional: true
    path "Networks/*2targets*.txt", emit: all_regulator_targets
    path "Networks/LemonNetwork_*.txt", emit: main_network
    path "Networks/Cytoscape_*.txt", emit: network_files
    path "Networks/*_distribution_plot_*.png", emit: distribution_plots, optional: true
    path "Networks/Network_*_ranked_regulators_*.txt", emit: ranked_regulators, optional: true
    path "ModuleViewer_files/*", emit: viewer_files
    path "ModuleViewer_files/sample_mapping.mvf", emit: sample_mapping
    path "Networks/specific_modules.txt", emit: filtered_modules
    path "Networks/Module_coherence_scores.txt", emit: coherence_scores, optional: true
    path "Module_prioritization_coherence_*.txt", emit: module_prioritization, optional: true

    script:
    """
    # Create directory structure for network generation
    mkdir -p Lemon_out Preprocessing
    
    echo "=== Files staged by Nextflow ==="
    ls -la
    echo "================================="
    
    # Copy all lemontree_outputs to Lemon_out directory
    # These are staged directly in the work directory by Nextflow
    # Use -L to follow symlinks and copy actual file contents
    for file in ${lemontree_outputs}; do
        if [ -L "\$file" ]; then
            # If it's a symlink, copy the target
            cp -rL "\$file" ./Lemon_out/
        elif [ -f "\$file" ]; then
            # If it's a regular file, copy it directly
            cp "\$file" ./Lemon_out/
        elif [ -d "\$file" ]; then
            # If it's a directory, copy it recursively
            cp -r "\$file" ./Lemon_out/
        fi
    done
    
    # Copy all preprocessing_files to Preprocessing directory
    for file in ${preprocessing_files}; do
        if [ -L "\$file" ]; then
            cp -L "\$file" ./Preprocessing/
        else
            cp "\$file" ./Preprocessing/
        fi
    done
    
    # List available files for debugging
    echo "=== Available files before network generation ==="
    echo "=== Lemon_out contents ==="
    ls -la Lemon_out/
    find Lemon_out/ -name "*.allreg.txt" -o -name "*.topreg.txt"
    echo "=== Preprocessing contents ==="
    ls -la Preprocessing/
    echo "================================================="
    
    # Run network generation script
    echo "Running network generation..."
    # Check host script first (allows updates without rebuilding container)
    if [ -f "${projectDir}/scripts/lemontree_to_network.py" ]; then
        SCRIPT_PATH="${projectDir}/scripts/lemontree_to_network.py"
    elif [ -f "/app/scripts/lemontree_to_network.py" ]; then
        SCRIPT_PATH="/app/scripts/lemontree_to_network.py"
    else
        echo "Error: lemontree_to_network.py not found"
        exit 1
    fi
    python3 \$SCRIPT_PATH \
        --input_dir . \
        --output_dir . \
        --run_id ${run_id} \
        --coherence_threshold ${params.coherence_threshold} \
        --regulator_selection_method ${params.regulator_selection_method} \
        --top_n_percent_regulators ${params.top_n_percent_regulators} \
        --regulator_fold_cutoff ${params.regulator_fold_cutoff} \
        --regulator_types "${params.regulator_types}"
    """

    stub:
    """
    mkdir -p Networks ModuleViewer_files
    touch Networks/networks.txt
    touch ModuleViewer_files/filtered_modules.txt
    touch ModuleViewer_files/sample_mapping.mvf
    """
}

process SUBNETWORK_GRAPHS {
    tag "Creating subnetwork visualization graphs"
    publishDir "${(params.output_dir ?: (params.input_dir ? params.input_dir + '/results' : './results'))}/${(params.computed_run_id ?: (params.run_id ?: 'run_auto'))}/LemonTree", mode: 'copy'

    input:
    path viewer_files
    path preprocessing_files
    val run_id

    output:
    path "Networks/subnetworks/graph_*.png", emit: subnetwork_graphs, optional: true
    path "Networks/cytoscape/*.tsv", emit: cytoscape_files, optional: true

    script:
    """
    # Create directory structure
    mkdir -p Lemon_out ModuleViewer_files Preprocessing Networks/subnetworks
    
    echo "=== Files staged by Nextflow ==="
    ls -la
    echo "================================="
    
    # Copy all viewer files to ModuleViewer_files
    for file in ${viewer_files}; do
        cp "\$file" ./ModuleViewer_files/
    done
    
    # Copy all preprocessing files to Preprocessing
    for file in ${preprocessing_files}; do
        cp "\$file" ./Preprocessing/
    done
    
    echo "=== ModuleViewer_files contents ==="
    ls -la ModuleViewer_files/
    echo "=== Preprocessing contents ==="
    ls -la Preprocessing/
    echo "================================="
    
    # Find all regulator files dynamically based on regulator_types parameter
    REGULATOR_FILES=""
    REGULATOR_TYPES="${params.regulator_types}"
    
    # Parse regulator types and find corresponding files
    IFS=',' read -ra TYPE_ARRAY <<< "\$REGULATOR_TYPES"
    for type_config in "\${TYPE_ARRAY[@]}"; do
        # Extract prefix (before colon)
        PREFIX=\$(echo "\$type_config" | cut -d':' -f1)
        
        # Find the corresponding regulator file using lowercase prefix
        PREFIX_LOWER=\$(echo "\$PREFIX" | tr '[:upper:]' '[:lower:]')
        REG_FILE=\$(find ModuleViewer_files -name "\${PREFIX}.*" -type f | head -1)
        
        if [ -n "\$REG_FILE" ]; then
            if [ -z "\$REGULATOR_FILES" ]; then
                REGULATOR_FILES="\${PREFIX}:\${REG_FILE}"
            else
                REGULATOR_FILES="\${REGULATOR_FILES},\${PREFIX}:\${REG_FILE}"
            fi
            echo "Found \${PREFIX} regulators: \${REG_FILE}"
        else
            echo "WARNING: \${PREFIX} regulators file not found"
        fi
    done
    
    # Check if we have any regulator files
    if [ -z "\$REGULATOR_FILES" ]; then
        echo "WARNING: No regulator files found, skipping subnetwork graphs"
        exit 0
    fi
    
    # Find clusters file
    CLUSTERS_FILE=\$(find . -name "clusters_list.txt" -o -name "specific_modules.txt" | head -1)
    if [ -z "\$CLUSTERS_FILE" ] || [ ! -f "\$CLUSTERS_FILE" ]; then
        echo "WARNING: Clusters file not found, skipping subnetwork graphs"
        exit 0
    fi
    
    # Copy clusters file to expected location
    mkdir -p ./Lemon_out
    cp "\$CLUSTERS_FILE" ./Lemon_out/clusters_list.txt
    
    # Run subnetwork graph generation
    echo "Creating subnetwork visualization graphs..."
    # Check host script first (allows updates without rebuilding container)
    if [ -f "${projectDir}/scripts/create_subnetwork_graphs.py" ]; then
        SCRIPT_PATH="${projectDir}/scripts/create_subnetwork_graphs.py"
    elif [ -f "/app/scripts/create_subnetwork_graphs.py" ]; then
        SCRIPT_PATH="/app/scripts/create_subnetwork_graphs.py"
    else
        echo "Error: create_subnetwork_graphs.py not found"
        exit 1
    fi
    
    # Check if metabolite mapping exists and build argument conditionally
    METABOLITE_ARG=""
    if [ -f ./Preprocessing/name_map.csv ]; then
        METABOLITE_ARG="--metabolite_mapping ./Preprocessing/name_map.csv"
        echo "Using metabolite mapping file: ./Preprocessing/name_map.csv"
    else
        echo "No metabolite mapping file found - proceeding without metabolite name mapping"
    fi
    
    python3 \$SCRIPT_PATH \
        --regulator_files "\$REGULATOR_FILES" \
        --clusters ./Lemon_out/clusters_list.txt \
        --pkn ${params.pkn_network} \
        \$METABOLITE_ARG \
        --output_dir ./Networks/subnetworks
    
    echo "Subnetwork graphs created successfully"
    """

    stub:
    """
    mkdir -p Networks/subnetworks
    touch Networks/subnetworks/graph_0.png
    """
}
