"""
PKN annotator module for adding database URLs to interactions.

URLs are generated by each individual retriever during Step 1 and stored
in the 'url' column of the processed cache files.  The combiner passes them
through intact into the final PKN.  This module reports coverage statistics
and writes the annotated output file.
"""

import pandas as pd
import logging
import sys
import os

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import config


def annotate_pkn() -> pd.DataFrame:
    """
    Finalise the annotated PKN by reporting URL coverage statistics
    and writing the output file.  URLs are already embedded in the
    'url' column that flowed from the Step-1 retrievers through the
    combiner; no regeneration is required here.

    Returns:
    --------
    pd.DataFrame
        Annotated PKN with URL column
    """
    logger = logging.getLogger('annotator')
    logger.info("="*80)
    logger.info("ANNOTATING PKN WITH DATABASE URLS")
    logger.info("="*80)

    # Load final PKN (url column already populated by retrievers)
    logger.info(f"\nLoading final PKN from: {config.FINAL_PKN_FILE}")
    pkn = pd.read_csv(config.FINAL_PKN_FILE, sep='\t')

    logger.info(f"  Total interactions: {len(pkn)}")

    # Rename lowercase 'url' → 'URL' for consistency with the output format
    if 'url' in pkn.columns and 'URL' not in pkn.columns:
        pkn = pkn.rename(columns={'url': 'URL'})
    elif 'URL' not in pkn.columns:
        pkn['URL'] = ''

    # Fill NaN urls with empty string
    pkn['URL'] = pkn['URL'].fillna('')

    # Report coverage statistics
    met_gene_mask = pkn['Type'] == 'metabolite-gene'
    ppi_mask = pkn['Type'] == 'PPI'
    met_gene_with_url = (met_gene_mask & (pkn['URL'] != '')).sum()
    logger.info(f"\nURL coverage summary:")
    logger.info(f"  Metabolite-gene interactions: {met_gene_mask.sum()}")
    logger.info(f"    With URL: {met_gene_with_url} ({100*met_gene_with_url/max(met_gene_mask.sum(),1):.1f}%)")
    logger.info(f"  PPI interactions: {ppi_mask.sum()} (no URLs expected)")
    logger.info(f"  Total with URL: {(pkn['URL'] != '').sum()}")

    # Log per-source URL coverage for metabolite-gene interactions
    if met_gene_mask.sum() > 0:
        logger.info("\n  Per-source URL coverage:")
        for src, grp in pkn[met_gene_mask].groupby('Source'):
            n_total = len(grp)
            n_url = (grp['URL'] != '').sum()
            logger.info(f"    {src}: {n_url}/{n_total} ({100*n_url/n_total:.1f}%)")

    # Save annotated PKN
    output_file = config.FINAL_PKN_WITH_LINKS_FILE
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    pkn.to_csv(output_file, sep='\t', index=False)
    logger.info(f"\n  Saved to: {output_file}")

    return pkn


if __name__ == '__main__':
    # Test annotator
    import logging
    logging.basicConfig(level=logging.INFO)

    annotated = annotate_pkn()

    print(f"\nAnnotated PKN:")
    print(f"  Total interactions: {len(annotated)}")
    print(f"  With URLs: {(annotated['URL'] != '').sum()}")
    print(annotated[annotated['URL'] != ''].head(10))

