#!/bin/bash -euo pipefail
# Create Lemon_out directory and copy cluster results
mkdir -p Lemon_out/Lemon_results

# Copy cluster results to Lemon_results subdirectory
# Note: cluster files can be either files or directories depending on LemonTree output
# Use cp -rL to dereference symlinks so downstream processes (which may not
# have the CLUSTERING work dirs bind-mounted) get actual file contents.
for cluster_item in Lemon_results/cluster_*; do
    if [ -e "$cluster_item" ]; then
        cp -rL "$cluster_item" Lemon_out/Lemon_results/
    fi
done

# Copy LemonTree input files to Preprocessing directory
mkdir -p Preprocessing

# Symlink data directory so regulator files (e.g. Histone_proteomics.csv) are found
ln -s data ./data 2>/dev/null || true

# List what we have available
echo "=== Available staged files ==="
ls -la
echo "============================="

# Copy all staged files to Preprocessing directory
# Nextflow stages the files directly in the work directory
for file in DESeq_groups.txt LemonPreprocessed_complete.txt LemonPreprocessed_expression.txt LemonPreprocessed_hPTM.txt LemonPreprocessed_metabolomics.txt LemonPreprocessed_proteomics.txt PCA_hptm.pdf PCA_metabolomics.pdf PCA_proteomics.pdf hptms.txt metabolites.txt name_mapping.tsv; do
    cp "$file" ./Preprocessing/
done

# Verify files were copied
echo "=== Files in Preprocessing directory ==="
ls -la ./Preprocessing/
echo "========================================"

# Run LemonTree post-clustering analysis (tight clusters and regulators)
echo "Running LemonTree post-clustering analysis..."
# Check host script first (allows updates without rebuilding container)
if [ -f "/home/borisvdm/repo/LemonIte/nextflow/scripts/lemontree_post_clustering.sh" ]; then
    SCRIPT_PATH="/home/borisvdm/repo/LemonIte/nextflow/scripts/lemontree_post_clustering.sh"
elif [ -f "/app/scripts/lemontree_post_clustering.sh" ]; then
    SCRIPT_PATH="/app/scripts/lemontree_post_clustering.sh"
else
    echo "Error: lemontree_post_clustering.sh not found"
    exit 1
fi
bash $SCRIPT_PATH         "hPTMs:Histone_proteomics.csv,Metabolites:metabolomics_combined.csv"         "/home/borisvdm/repo/LemonIte/nextflow/LemonTree/lemontree_v3.1.1.jar"         .         "human"         "0.1"

# List generated files for debugging
echo "=== Files generated by post-clustering ==="
find Lemon_out -type f -name "*.txt" | head -20
echo "=========================================="
